[phases.setup]
nixPkgs = ["python311", "postgresql", "git"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'print(\"Build completed\")'"]

[start]
cmd = "python app.py"